// SPDX-License-Identifier: MIT
//! Data models and DTOs exchanged via WebSocket.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Messages sent from the CLI Server to remote connected Clients.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ServerMessage {
    /// Full state synchronization.
    #[serde(rename = "state_update")]
    StateUpdate(SessionStateDto),

    /// A chunk of streaming text just generated by the model.
    #[serde(rename = "stream_chunk")]
    StreamChunk { text: String },

    /// The agent started executing a tool.
    #[serde(rename = "tool_start")]
    ToolStart { tool_name: String, args: String },

    /// The agent finished executing a tool.
    #[serde(rename = "tool_finish")]
    ToolFinish { output_summary: String },

    /// A notification to display to the user.
    #[serde(rename = "notification")]
    Notification { level: String, message: String },
}

/// Messages sent from the remote Client to the CLI Server.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ClientMessage {
    /// User typed a message in the remote terminal.
    #[serde(rename = "user_input")]
    UserInput { content: String },

    /// Pause the active agent execution.
    #[serde(rename = "pause")]
    PauseExecution,

    /// Cancel the active agent execution.
    #[serde(rename = "cancel")]
    CancelExecution,

    /// Approve a pending tool call directly from the remote client.
    #[serde(rename = "approve_tool")]
    ApproveTool,

    /// Reject a pending tool call.
    #[serde(rename = "reject_tool")]
    RejectTool { reason: Option<String> },
}

/// Represents the current state of an ARC CLI session.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SessionStateDto {
    pub session_id: String,
    pub working_dir: String,
    pub status: AgentStatus,
    pub pending_approval: bool,
    pub current_task: Option<String>,
    pub last_updated: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub enum AgentStatus {
    #[default]
    Idle,
    Thinking,
    ExecutingTool,
    WaitingForApproval,
    Paused,
}
